import {Component} from "@angular/core";
import {Router} from "@angular/router";
import {SwitchBoard} from "qCommon/app/services/SwitchBoard";
import {Session} from "qCommon/app/services/Session";
import {CompanyUsers} from "qCommon/app/services/CompanyUsers.service";
import {ToastService} from "qCommon/app/services/Toast.service";
import {TOAST_TYPE} from "qCommon/app/constants/Qount.constants";

@Component({
  'selector': 'terms-conditions',
  'templateUrl': '../views/TermsAndConditions.html'
})

export class TermsAndConditionsComponent {

  termsAndConditionsText: string;
  constructor(private _router: Router, private switchBoard: SwitchBoard, private companyUsersService: CompanyUsers,
              private toastService: ToastService) {
    this.termsAndConditionsText = "For the purposes of this Agreement, Qount includes QountHQ Inc and American SMB Services LLC\n\n" +
      "Please read these terms of use (“Agreement” or “Terms of use”) carefully before using the services offered by QountHQ Inc and American" +
      " SMB Services LLC (“Qount”). This agreement sets forth the legally binding terms and conditions for you and your business or other legal" +
      " entity’s (referred as “you” or “Customer”) use of the various websites owned and operated by company, including, without limitation, " +
      "the www.qount.io website and other domain names (“Sites”), any mobile applications (each an “App”), other internet services under " +
      "Company’s control and any other features, content, or applications offered from time to time in connection therewith (collectively, the" +
      " “Services”). By using the sites, apps or service in any manner, including but not limited to visiting or browsing the sites, you agree" +
      " to be bound by this agreement. This agreement applies to all users of the sites, apps or service, including users who are also" +
      " contributors of content, information, and other materials or services on the sites. By entering into this agreement on behalf of a" +
      " company or other legal entity, you represent that you have the authority to bind such entity to this agreement and that you are of" +
      " legal age to form a binding contract.\n\n" +
      "DEFINITIONS\n\n" +
      "•	Customer, means you or if you are using the service on behalf of an entity, organization, partnership on whose behalf you are utilizing" +
      " the services.\n\n" +
      "•	Party, means either Qount or Customer and Parties, mean Qount and Customer.\n\n" +
      "1.\tACCEPTANCE OF TERMS\n\n" +
      "1.1.\tThe Service is offered subject to acceptance without modification of these Terms of Use and all other operating rules, policies and" +
      " procedures that may be published from time to time on the Sites by Company. In addition, some services offered through the Service may be" +
      " subject to additional terms and conditions promulgated by Company from time to time; your use of such services is subject to those" +
      " additional terms and conditions, which are incorporated into these Terms of Use by this reference. The Service is available for business" +
      " use and for use by individual consumers to manage personal tax returns. You represent and warrant that all registration information you" +
      " submit is accurate and truthful; and that your use of the Service does not violate any applicable law or regulation. Company may, in its" +
      " sole discretion, refuse to offer the Service to any entity and change its eligibility criteria at any time. This provision is void where" +
      " prohibited by law and the right to access the Service is revoked in such jurisdictions.\n\n" +
      "2.\tSERVICES\n\n" +
      "2.1.	Scope of Services. Qount agrees to provide the Services as may be described in separate Engagement Letter that outlines the scope of" +
      " services to be performed.\n\n" +
      "2.2.	Compensation (Fees). Customer agrees to pay Qount the amounts set forth and at the times indicated as Fees for the Services included in" +
      " the Engagement Letter. Changes in scope or work requirements may occur over the course of the arrangement and fees may or may not be" +
      " adjusted accordingly. Any changes will be communicated to Customer and will become effective as indicated in any such notice.\n\n" +
      "2.3.	Payment of Services. Customer agrees that fees will be invoiced in accordance with the terms set forth in the Engagement Letter." +
      "Invoices are due and payable upon receipt by Customer unless otherwise indicated. Customer is responsible for all applicable state and local" +
      " sales or use taxes. All invoices remaining unpaid after 30 days from the invoice date will incur a 1.5% finance charge per month and any delay in" +
      " payments beyond the established terms may result in the immediate suspension of services.\n\n" +
      "2.4.\tConditions of Relationship. Qount’s relationship with Customer will be that of an independent contractor and nothing in this Agreement should" +
      " be construed to create a partnership, joint venture, or employer-employee relationship. Qount is not the agent of Customer and is not" +
      " authorized to make any representation, contract, or commitment on behalf of Customer. Qount will not be entitled to any of the benefits," +
      " which Customer may make available to its employees, such as group insurance, profit sharing or retirement benefits. Qount shall be solely" +
      " responsible for all tax returns and payments required to be filed with or made to any federal, state or local tax authority with respect to" +
      " Qount’s performance of services and receipt of fees under the Engagement Letter.\n\n" +
      "2.5.\tScope and Approach. Qount will provide the Services described in the Engagement Letter in support of Customer’s effort to improve the" +
      " management of its business and to quantify the financial opportunities and/or threats indicated over a specified period of time. Although" +
      " Qount is fully capable of delivering such Products and Services, it is critical that Customer remain actively involved in the process to" +
      " ensure accuracy and continuity in the information. Customer acknowledges and agrees that no one knows Customer’s business better than its" +
      " owner(s) and staff and that all work must be conducted with full participation of Customer as and when necessary to ensure the quality of" +
      " the final product.  Customer further acknowledges and agrees that all final decisions regarding every aspect of its business are its sole" +
      " responsibility.\n\n" +
      "2.6.\tQount provides back office administration services to handle financial transactions, tax preparation and bookkeeping services mostly. None" +
      " of the services are assurance tasks and cannot be relied on to detect errors, frauds, irregularities, or illegal acts that may exist." +
      " However, Qount will inform you of any material errors that come to our attention and any irregularities or illegal acts that may come to" +
      " our attention, unless they are clearly inconsequential.\n\n" +
      "3.\tTERM AND TERMINATION\n\n" +
      "3.1.\tTerm. The term of this arrangement will be for successive one-month periods until terminated by either party.\n\n" +
      "3.2.\tTermination. Either party may terminate the Engagement Letter by providing thirty (30) days written notice of termination" +
      " to the other party. The termination date will be the last day of the month following the date of the termination notice.\n\n" +
      "3.3.\tEffect of Termination. In the event this Agreement is terminated for any reason, Qount shall deliver all Services indicated" +
      " in the Engagement Letter through the termination date provided that Customer is current on all outstanding invoices and Customer pays all" +
      " additional fees incurred in accordance with the terms of the Engagement Letter upon performance and delivery of the balance of the requested" +
      " Services. Unless mutually agreed to otherwise, upon termination, Customer agrees to return, or warrant in writing that they have deleted or" +
      " destroyed, any information or data that has been provided under the terms of the Engagement Letter.\n\n" +
      "4.\tINTELLECTUAL PROPERTY\n\n" +
      "4.1.\tAuthorized Use. Customer warrants that it owns or is fully authorized in every use of the information and/or data provided for purposes of the" +
      " Engagement Letter.\n\n" +
      "4.2.\tIntellectual Property Rights. Both parties acknowledge and agree that each has sole and exclusive rights to all of its patents, copyrights," +
      " trademarks, confidential technical information, trade secrets, and improvements as defined herein (collectively \"Intellectual Property" +
      " Rights\"). For greater certainty, Customer’s Intellectual Property Rights include, but are not limited to: Customer’s web pages and" +
      " databases, patents, trademarks, service marks, copyrights, logos, product information, designs, Created Materials and customer lists." +
      "  For greater certainty, Qount’s Intellectual Property Rights include, but are not limited to: all details of the Qount services, products" +
      " and technology, such as software systems, financial models, document templates, illustrations and schematics (excluding any data furnished" +
      " or formatted by Customer) offered. Each party shall have the sole and exclusive right, but not the obligation, to seek, pursue, prosecute" +
      " and maintain all intellectual property protection and government registrations for their respective Intellectual Property Rights. Each party" +
      " agrees that, if necessary, it will cooperate with the other party to obtain and maintain protection of its intellectual property, and" +
      " waives any and all claims and rights to the other party’s Intellectual Property Rights defined herein.\n\n" +
      "4.3.\tImprovements. Customer agrees that any tangible improvements, enhancements, upgrades, modifications and updates to any technical confidential information, Qount software, patents, copyrights or trade secrets (collectively \"Improvements\") developed by Qount including those developed by Qount at the request of, or specifically for, Customer shall be the property of Qount.\n\n" +
      "4.4.\tFeedback. In the event that Customer provides Qount any ideas, thoughts, criticisms, suggested improvements or other feedback related to the Services (collectively “Feedback”), Customer agrees that Qount may use the Feedback to modify the Services and that Customer will not be due any compensation, including any royalty related to the product or service that incorporates the Feedback. Customer hereby grants Qount a worldwide, royalty-free, fully paid, perpetual, irrevocable license to use, reproduce, modify, translate, distribute, perform, display, import, sell, offer for sale, make, have made and otherwise exploit the Feedback in any form, media, or technology, whether now known or hereafter developed, and to allow others to do the same. This is true whether Customer provides the Feedback on the Services or through any other method of communication with Qount.\n\n" +
      "4.5.\tRights on Termination. All rights to use each other’s Intellectual Property Rights terminate with the termination of the Engagement Letter, and no license rights, express or implied, shall survive the termination of the Engagement Letter. Neither party will use the confidential information, the Intellectual Property nor Created Materials defined herein in a manner that would infringe on the other party’s rights.\n\n" +
      "5.\tNON DISCLOSURE\n\n" +
      "5.1.\tNon Disclosure & Confidentiality. “Confidential Information” means proprietary techniques and confidential information that the either party and/or any of its affiliates has or will develop, compile, or own, or that the either party and/or any of its affiliates receives under conditions of confidentiality from its customers.  Confidential Information includes not only information disclosed by either party and/or any of its affiliates (including its employees, agents, independent contractors, and consultants) to the other party in connection with the Referring Party’s duties, but also information developed or learned by either party during the course of Referring Party’s engagement by the Company.  Confidential Information is to be broadly defined and includes, but is not limited to, trade secrets, financial data, business and marketing strategies, business operations, strategy and plans of each party and its affiliates and their respective financial information including revenues, expenses, profits, employee names and positions, employee compensation and benefits, customer names and preferences, and supplier costs and arrangements.  At all times during and after the Engagement Period, except as required by applicable law or court proceeding, each party will hold in trust, keep confidential, not make use of (or allow others to make use of), and not disclose or reveal to any third party any Confidential Information of the other party.  Each party acknowledges that the unauthorized use or disclosure of Confidential Information may be highly prejudicial to the interests of the other party, its affiliates or their respective customers, an invasion of privacy, or an improper disclosure of trade secrets.\n\n" +
      "5.2.\tNon-Solicitation. Customer and Qount specifically agrees that during a period of two (2) years following the last date that Qount provides the Services, Customer or related parties shall not, either on his / her own or as a shareholder, principal, agent, contractor, manager, advisor, director, officer, control person, operator, or in any other capacity or manner whatsoever, directly or indirectly, hire, solicit, seek to hire, seek to retain, or offer employment to any person who was employed by or under contract with Qount during the twelve (12) months prior to the date Qount last provided services.\n\n" +
      "6.\tDATA PRIVACY AND SECURITY\n\n" +
      "6.1.\tThe Company does not share customer information of any kind with anyone. Company will not sell or rent your name or personal information to any third party. Company does not sell, rent or provide outside access to our mailing list or any data we store. Any data that a user stores via our facilities is wholly owned by that user or business. At anytime a user or business is free to take their data and leave, or to simply delete their data from our facilities.\n\n" +
      "6.2.\tCompany only collects such personal information that is necessary for you to access and use our services. This personal information includes, but is not limited to, first and last name, physical address, zip code, email address, phone number, financial information, and other personal information necessary to generate proper financial, tax and compliance documents to provide Services.\n\n" +
      "6.3.\tCompany reserves the right to cooperate with local, state, provincial and national authorities in investigations of improper or unlawful activities and this may require the disclosure of Customer’s personal information. Company may also report to other organizations about improper or unlawful user activities and this reporting may include disclosure of personal information relating to those individuals conducting such improper or unlawful activities. Company may release personal information if required by law, search warrant, subpoena, court order or fraud investigation. Company may also use personal information in a manner that does not identify you specifically nor allow you to be contacted but does identify certain criteria in general.\n\n" +
      "6.4.\tThe Company knows that privacy is important. The security of your personal information is of highest priority. While there is no such thing as “perfect security” on the Internet, the Company will take reasonable steps to help protect your personal information. However, you understand and agree that such steps do not guarantee that the Services are invulnerable to all security breaches or immune from viruses, security threats or other vulnerabilities.\n\n" +
      "6.5.\tData Security. The security of your personal, business and financial information is important to us. When you enter sensitive information on our order forms, we encrypt the transmission of that information using secure socket layer technology (SSL). We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, we cannot guarantee its absolute security.\n\n" +
      "6.6.\tPlease refer to https://www.qount.io/security for more information on security.\n\n" +
      "7.\tUID SETUP AND USAGE\n\n" +
      "7.1.\tAs a condition to using certain aspects of the Service, Customer will be required to register with Company and select a password and screen name (“UID”). Customer shall provide Company with accurate, complete, and updated registration information. Failure to do so shall constitute a breach of the Terms of Use, which may result in immediate termination of Customer’s Company account. Customer shall not (i) select or use as a UID a name of another person with the intent to impersonate that person; (ii) use as a UID a name subject to any rights of a person other than Customer without appropriate authorization; or (iii) use as a UID a name that is otherwise offensive, vulgar or obscene. Company reserves the right to refuse registration of, or cancel a UID in its sole discretion. Customers are solely responsible for activity that occurs on Customer’s account and shall be responsible for maintaining the confidentiality of Customer’s Company password. Customer shall never use another user’s account without such other user’s express permission. Customer will immediately notify Company in writing of any unauthorized use of Customer’s account, or other account related security breach of which Customer are aware.\n\n" +
      "7.2.\tSubject to Customer’s complete and ongoing compliance with all the terms and conditions of this Agreement and payment of all applicable fees, Company hereby grants to Customer a personal, limited, revocable, non-exclusive, non-sublicensable, non-transferable license during the Term, to access and use the Services through Company’s available interfaces and to permit Customer and Customer’s users to access and use the Services through Company’s available interfaces, in each case, solely in connection with Customer’s business operations.\n\n" +
      "7.3.\tUpon Customer’s request, Company will issue a UID or Customer can setup Customer’s own UIDs for use of our Services. Customer may share this UID with each of Customer’s partners, shareholders, employees and contractors who are bound by confidentiality restrictions at least as restrictive as this Agreement. Everyone may only access and use the Service through a valid UID and in compliance with this Agreement. Customer should not allow sharing of UID and passwords with third parties. Customer are responsible for all activity occurring under its UID. Company reserves the right to replace the UIDs if it determines it may have been used for an unauthorized purpose.\n\n" +
      "7.4.\tCompany may make the Services available for access via the Internet. Customer shall provide, at Customer’s own expense, all necessary hardware, applications and Internet connectivity necessary to access the Services. Customer acknowledge that the Internet is known to be unpredictable in performance, unsecure and may, from time to time, impede access to the Services or performance hereunder. Customer agrees that Company is not in any way responsible for any interference with Customer’s use of or access to the Services or security breaches arising from or attributable to the Internet and Customer waives any and all claims against Company in connection therewith.\n\n" +
      "7.5.\tCustomer agree that Customer will not: (i) permit any party to access or use the Services other than the users authorized; (ii) modify, adapt, alter or translate any software underlying the Services, except as expressly allowed hereunder; (iii) sublicense, lease, rent, loan, distribute, or otherwise transfer the Service to any third party; (iv) except if, and solely to the extent that, such a restriction is impermissible under applicable law, reverse engineer, decompile, disassemble, or otherwise derive or determine or attempt to derive or determine the source code (or algorithms, structure or organization) of any software underlying the Services; (v) use or copy the any software underlying the Services except as expressly allowed hereunder; (vi) conduct or promote any illegal activities while using the Services; (vii) use the Services to generate unsolicited email advertisements or spam; (viii) use the Services to stalk, harass or harm another individual; (ix) use any high volume automatic, electronic or manual process to access, search or harvest information from the Services (including without limitation robots, spiders or scripts); (x) except if, and solely to the extent that, such a restriction is impermissible under applicable law, interfere in any way with the proper functioning of the Services or interfere with or disrupt any servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services; (xi) attempt to gain access to secured portions of the Services to which it does not possess access rights; (xii) upload or transmit any form of virus, worm, Trojan horse, or other malicious code; (xiii) use any robot, spider, other automatic device, or manual process to extract, “screen scrape”, monitor, “mine”, or copy any static or dynamic web page on the Services or the content contained on any such web page for commercial use without our prior express written permission; (xiv) impersonate any person or entity, or otherwise misrepresent its affiliation with a person or entity; (xv) mirror or frame the Services or any content, place pop-up windows over its pages, or otherwise affect the display of its pages; or (xvi) publicly display or publicly perform any part of the Services. Customer may not use the Services for any purpose other than a purpose for which the Services are expressly designed. If Customer is prohibited under applicable law from using the Services, Customer may not use them.\n\n" +
      "8.\tTHIRD PARTY INFORMATION ACCESS\n\n" +
      "8.1.\tCustomer may direct Company to retrieve certain information maintained online by third-party financial institutions or providers with which Customer have a relationship, maintain accounts or engage in financial transactions (“Account Info”). Customer agree to provide Customer’s username, password, PIN and other log-in information and credentials necessary to access Customer’s account with such institutions or providers (“Access Info”), and Customer hereby grant Company permission to use the Access Info and Account Info for the purposes contemplated by this Agreement.\n\n" +
      "8.2.\tBy using the Service, Customer expressly authorize Company to access, store and use Customer’s Account Info maintained by identified third parties, on Customer’s behalf as Customer’s agent. Customer hereby authorize Company to store and use Customer’s Access Info to accomplish the foregoing and to configure the Service so that it is compatible with the third party sites for which Customer submit Account Info. This may include, without limitation, monitoring Customer’s usage (including the location of relevant clicks and links) of such third party sites (when accessed through the Service) solely to facilitate such compatibility and our contemplated access to Customer’s relevant Account Info in connection with the Service. For purposes of this Agreement, Customer grant Company a limited power of attorney, and appoint Company as Customer’s attorney-in-fact and agent, to access third party sites using Access Info, and to retrieve, store and use Customer’s Account Info with the full power and authority to do and perform each thing necessary in connection with such activities, as Customer could do in person solely in connection with Company’s provision of the Service. Customer acknowledge and agree that when company accesses and retrieves account info from third party sites, company is acting as Customer’s agent, and not as the agent of or on behalf of the third party. Customer acknowledge and agree that the foregoing does not imply sponsorship or endorsement by any third party services accessible through the Service. Customer represent and warrant that neither the foregoing (or anything else in this Agreement) nor Customer’s use of the Services will violate any agreement or terms to which Customer are subject, including without limitation, those with respect to any third party site or service.\n\n" +
      "9.\tSUPPORT\n\n" +
      "9.1.\tSupport. During the Term for the applicable Services, and for so long as Customer is current with its payment of all applicable fees, Qount will use commercially reasonable efforts to provide Customer with technical support services relating to the Services via website, email, telephone or any other means as Qount deems fit.\n\n" +
      "9.2.\tService Upgrades and Scheduled Downtime. Qount may update the Services in its sole discretion. Qount may from time to time schedule downtime for maintenance and upgrades.\n\n" +
      "9.3.\tCall Monitoring. Qount may monitor and record support-related and other outbound calls to Customer, as well as inbound calls to Qount by Customer or Customer’s representatives, for compliance, support, training and other purposes. Customer acknowledges and agrees that Qount may record any call between Customer and Qount relating to the Service, and agrees to (i) notify all relevant Customer employees that calls with Qount may be monitored and (ii) indemnify and hold harmless Qount from any claim arising as a result of Qount’s monitoring or recording of calls between Qount and Customer’s representatives.\n\n" +
      "10.\tLIMITATION OF LIABILITIES\n\n" +
      "10.1.\tThe Parties acknowledge that each provision of this Agreement that provides for a limitation of liability, disclaimer of warranties, or exclusion of damages is intended to and does reflect a fair allocation of risk between the parties, and this allocation of risk forms an essential element of the basis of the bargain between the parties and shall survive and continue in full force and effect despite any failure of consideration or of an exclusive remedy. Each of these provisions is severable and independent of all other provisions of this Agreement. The limitations in this section will apply even if any limited remedy fails of its essential purpose.\n\n" +
      "10.2.\tLimit of Liability. Qount is totally dependent on the information received from Customer and other sources available in the public domain and cannot be held responsible for the accuracy of the information received. Qount will use its best efforts to verify any information it gathers independently in support of the Services described in the Engagement Letter.  However, Qount does not warrant or make any representations about the suitability of the information supplied by the Customer. Qount will not be liable for loss of use, interruption of business or lost profits however. In the event of claim Qount’s liability is strictly limited to the fees paid in the last [3] six months by Customer under the Engagement Letter.\n\n" +
      "10.3.\tIn no event shall qount be liable to customer for any (i) special, indirect, incidental, punitive or consequential damages, (ii) lost savings, profits, data, use, or goodwill, (iii) business interruption even if notified in advance of such possibility, or (iv) personal or property damage arising out of or in any way connected to this eula, regardless of cause of action or the theory of liability, whether in contract, tort (including negligence, gross negligence, fundamental breach, breach of a fundamental term) or otherwise. In no event shall qount be liable for procurement or costs of substitute products or services. The foregoing limitations will apply notwithstanding any failure of essential purpose of any limited remedy herein.\n\n" +
      "10.4.\tSome of the above limitations and disclaimers may not apply to customer. To the extent that qount may not, as a matter of applicable law, disclaim any implied warranty or limit liabilities, the scope and duration of such warranty and the extent of qount’s liability will be the minimum permitted under such applicable law.\n\n" +
      "11.\tARBITRATION\n\n" +
      "11.1.\tArbitration. Except as expressly provided in this Agreement, all controversies, disputes, demands, counts, claims, or causes of action between Customer and Qount arising out of, under, or related to this Agreement or Qount’s privacy practices shall be settled exclusively through binding arbitration.\n\n" +
      "11.2.\tArbitration shall be subject to the Federal Arbitration Act and not any state arbitration law. The arbitration shall be conducted before one commercial arbitrator with substantial experience in resolving commercial contract disputes from the American Arbitration Association (“AAA”). As modified by this Agreement, and unless agreed upon by the parties in writing, the arbitration will be governed by the AAA’s Commercial Arbitration Rules and, if the arbitrator deems them applicable, the Supplementary Procedures for Consumer Related Disputes (collectively “Rules and Procedures”).\n\n" +
      "11.3.\tArbitration is less formal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. This Agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of this Agreement, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of this Agreement. Customer understands and agrees that, by entering into this agreement, customer and qount are each waiving the right to a trial by jury or to participate in a class action.\n\n" +
      "11.4.\tCustomer and Qount must abide by the following rules: (a) for any claim that could otherwise be brought in small claims court, the arbitration shall be conducted solely based on written submissions and, if the arbitrator deems it appropriate, a telephonic hearing; (b) if the claim exceeds what can be recovered in a small claims court, the arbitration shall be conducted solely based on written submissions or a telephonic hearing, unless the arbitrator deems a face-to-face hearing is appropriate, in which case one should be held at a location agreed to by Customer and Qount, and if the parties cannot agree on a location for the hearing, the arbitrator will determine a location for the proceedings which is reasonably convenient to both parties with due consideration of their ability to travel and other pertinent circumstances; (c) the arbitrator’s ruling is binding and not merely advisory; (d) any claims brought by customer or Qount must be brought in the parties’ individual capacity, and not as a plaintiff or class member in any purported class or representative proceeding; (e) the arbitrator mat not consolidate more than one person’s claims, and may not otherwise preside over any form of representative or class proceeding, (f) in the event that Customer is able to demonstrate that the costs of arbitration will be prohibitive as compared to costs of litigation, Qount will pay as much of Customer’s filing and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive as compared to the cost of litigation, (g) Qount also reserves the right in its sole and exclusive discretion to assume responsibility for all of the costs of the arbitration; (h) the arbitrator shall honor claims of privilege and privacy recognized at law; (i) a decision by the arbitrator (including any finding of fact and/or conclusion of law) against either Customer or Qount shall be confidential unless otherwise required to be disclosed by law or by any administrative body and may not be collaterally used against either of them in existing or subsequent litigation or arbitration involving any other person/Qount customer; and (j) each side pays its own attorneys’ fees and expenses unless there is a statutory provision that requires the prevailing party to be paid its fees’ and litigation expenses.\n\n" +
      "11.5.\tNotwithstanding the foregoing, either Customer or Qount may bring an individual action in small claims court. In addition, if Customer is a user outside of the United States, the dispute resolution provision in our Privacy Policy (if any), and not this arbitration provision, shall apply to any disputes related to privacy. Further, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark, or trade secret shall not be subject to this arbitration provision. Such claims shall be exclusively brought (unless such courts do not have personal jurisdiction in the dispute) in the courts located in the State of Texas. Additionally, notwithstanding this arbitration provision, either party may seek emergency equitable relief before such courts in order to maintain the status quo pending the arbitrator’s ruling, and hereby agree to submit to the personal jurisdiction of such courts. A request for interim measures shall not be deemed a waiver of the right to arbitrate.\n\n" +
      "11.6.\tWith the exception of content in this Section 11 prohibiting arbitration on a class or collective basis, if any part of this arbitration provision is deemed to be invalid, unenforceable or illegal, or otherwise conflicts with the Rules and Procedures, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting provision were not contained herein. In the event this arbitration provision is held unenforceable by a court, or in the event AAA refuses to arbitrate the dispute, all controversies, disputes, demands, counts, claims, or causes of action between Customer and Qount shall be exclusively brought in the state or federal courts located in Collin County, Texas. For more information on AAA, its Rules and Procedures, and how to file an arbitration claim, Customer may call AAA or visit the AAA website at http://www.adr.org.\n\n" +
      "12.\tOTHER PROVISIONS\n\n" +
      "12.1.\tWarranty Disclaimer. Company has no special relationship with or fiduciary duty to Customer. Customer acknowledges that Company has no control over, and no duty to take any action regarding: which users gain access to the Services; what Content Customer access via the Services; what effects the Content may have on Customer; how Customer may interpret or use the Content; or what actions Customer may take as a result of having been exposed to the Content. Customer releases Company from all liability for Customer having acquired or not acquired Content through the Services. The Services may contain, or direct Customer to websites containing, information that some people may find offensive or inappropriate. Company makes no representations concerning any content contained in or accessed through the Services, and Company will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Services. Company makes no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services. The services, content, website and any software are provided on an “as is” basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or that use of the services will be uninterrupted or error-free. Some states do not allow limitations on how long an implied warranty lasts, so the above limitations may not apply to Customer.\n\n" +
      "12.2.\tSeverability. Should all or any portion of any provision of this Agreement be held unenforceable or invalid for any reason, the remaining portions or provisions shall be unaffected and this Agreement shall be construed as if such unenforceable or invalid provision had never been contained herein.\n\n" +
      "12.3.\tNo Consequential Damages/Liability. In no event shall either party be liable to the other for any claim, injury, demand or judgment based on tort, expressed or implied warranty, or for incidental, special, punitive or consequential damages to the other.\n\n" +
      "12.4.\tForce Majeure. Customer acknowledges and understands that if Qount is unable to provide Services as a result of a force majeure event Qount will not be in breach of this Agreement and will not be liable for delays caused by such event. A force majeure event means any event beyond the control of Qount.\n\n" +
      "12.5.\tGovernmental Approvals. Each party agrees to conform to all laws, regulations, ordinances and governmental policies that may be applicable to performance of these terms and those of the Engagement Letter.\n\n" +
      "12.6.\tAuthority. Customer and Qount each represent that they have the requisite power and authority to carry on their business as conducted. Each party further represents and warrants that it is qualified to do business in each jurisdiction in which it is necessary to perform obligations under the Engagement Letter.\n\n" +
      "12.7.\tGoverning Law. These Terms and the Engagement Letter shall be governed and construed in accordance with the laws of the State of Texas.\n\n" +
      "12.8.\tAttorney Fees. In the event of any proceeding relating to a dispute involving this Agreement or / and the Engagement Letter, the losing party shall pay the prevailing party's reasonable attorneys' fees and expenses incurred in any phase of the dispute.\n\n" +
      "12.9.\tOnline Communication & Collaboration. In connection with delivering the Services, Qount may communicate and collaborate with Customer or others via email transmission, online portals, online messaging and other electronic means via Qount and / or other third party software. As these means of data transmission can be intercepted and read, disclosed, or otherwise used or communicated by an unintended third party, or may not be delivered to each of the parties to whom they are directed and only to such parties, we cannot guarantee or warrant that information from us will be properly delivered and read only by the addressee. Therefore, we specifically disclaim and waive any liability or responsibility whatsoever for interception or unintentional disclosure of emails, messages, information transmitted by us in connection with the performance of this engagement. In that regard, Customer agree that we shall have no liability for any loss or damage to any person or entity resulting from the use of email transmissions, including any consequential, incidental, direct, indirect, or special damages, such as loss of revenues or anticipated profits, or disclosure or communication of confidential or proprietary information.\n\n" +
      "12.10.\tAny litigation arising out of this engagement, except actions by us to enforce payment of our professional invoices, must be filed within one year from the accrual of the cause of action, notwithstanding any statutory provision to the contrary. In the event of litigation brought against us, any judgment Customer obtain shall be limited in amount, and shall not exceed the amount of the annual fee charged by us, and paid by Customer, for the services set forth in this engagement letter.\n\n" +
      "12.11.\tIn the event we are required to respond to a subpoena, court order or other legal process for the production of documents and/or testimony relative to information we obtained and/or prepared during the course of this engagement, Customer agree to compensate us for the time we expend in connection with such response, and to reimburse us for all of our out-of-pocket costs incurred in that regard.\n\n" +
      "12.12.\tCustomer agrees that Qount may utilize Customer’s entity name in listings of current customers. Use of Customer’s name in any other marketing materials or press announcements will be submitted to Customer in advance for approval, and such approval will not be unreasonably withheld.\n\n" +
      "12.13.\tIn the event that we are or may be obligated to pay any cost, settlement, judgment, fine, penalty, or similar award or sanction as a result of a claim, investigation, or other proceeding instituted by any third party, and if such obligation is or may be a direct or indirect result of any inaccurate or incomplete information that Customer provide to us during the course of this engagement, Customer agree to indemnify us, defend us, and hold us harmless as against such obligation.\n\n" +
      "12.14.\tTaxes. All taxes charged by any governmental agency for services delivered by (excluding Qount’s income tax) will be passed on to Customer. State and local sales taxes will be added to all taxable services and shipments delivered within the state of Texas. All other taxes are the responsibility of each respective party.\n\n" +
      "12.15.\tAssignment. These Terms and the Engagement Letter shall not be assigned by Customer without Qount's prior written consent.\n\n" +
      "12.16.\tIndemnification. Each party shall defend, indemnify and hold the other and its respective members, shareholders, officers, directors, agents and employees harmless from and against any and all losses, liabilities, costs, expenses, damages, claims, demands, suits and judgments, including without limitation, attorneys fees, disbursements and costs of any legal action, arising out of their performance or omission of any obligations set forth in these Terms of Service and the Engagement Letter.\n\n" +
      "12.17.\tIndependent Contractors. The provisions of these Terms solely determine the relationship of the parties to the Engagement Letter. The parties do not intend to create any agency, partnership, joint venture, trust or other relationship with duties or incidents different from those of parties to an arms-length contract.\n\n" +
      "12.18.\tModifications. Company reserves the right, at its sole discretion, to modify or replace any of the Terms of Use, or change, suspend, or discontinue the Service (including without limitation, the availability of any feature, database, or content) at any time by posting a notice on the Sites or by sending Customer an email. Company may also impose limits on certain features and services or restrict Customer’s access to parts or all of the Service without notice or liability. It is Customer’s responsibility to check the Terms of Use periodically for changes. Customer’s continued use of the Service following the posting of any changes to the Terms of Use constitutes acceptance of those changes.\n\n";
    console.log("Terms and conditions component initialized...");
  }

  accept() {
    this.companyUsersService.acceptTerms(Session.getUser().default_company.id)
      .subscribe(resp => {
        this.switchBoard.onLogin.next(Session.get('user'));
        this._router.navigate(['']);
      }, error => {
        Session.destroy();
        let message = error.message || "Failed to accept Terms And Conditions.";
        this.toastService.pop(TOAST_TYPE.error, message);
        this.switchBoard.onLogOut.next({'loggedOut': true});
      });
    return false;
  }

  decline() {
    Session.destroy();
    this.switchBoard.onLogOut.next({'loggedOut': true});
  }
}
