/**
 * Created by seshu on 07-03-2016.
 */

export const PATH = {
  NODE_SERVICE_URL: 'https://dev-services.qount.io/BigHalfNode',
  ACTIVATE_USER: '/activate?token=:token',
  NOTIFICATIONS_URL: 'https://dev-services.qount.io:8081/socket.io',
  QOUNT_NOTIFICATIONS_URL: 'https://dev-services.qount.io:8081/qountnotifications',
  NOTIFICATIONS_PATH: '/notify/socket.io',
  JAVA_SERVICE_URL: 'https://dev-services.qount.io',
  SIGNUP_SERVICE: '/signup',
  EMAIL_SERVICE:'/email',
  LOGIN_SERVICE: '/login',
  FORGOT_PASSWORD_SERVICE: '/forgotpassword',
  RESET_PASSWORD_SERVICE: '/resetpassword',
  NOTIFICATIONS_SERVICE: '/notifications',
  UNREAD_NOTIFICATIONS_SERVICE: '/unreadNotifications',
  NOTIFICATIONS_COUNT: '/user/:userId/notificationscount',
  USER_SERVICE: '/HalfService/user',
  USERS_SERVICE: '/users?q=:prefix',
  USERS: '/users/',

  ACTIVATION_LINK:"https://dev-payments.qount.io",
  COMPANIES_SERVICE: '/HalfService/user/:id/companies',
  VENDOR_SERVICE: '/HalfService/user/:id/vendors',
  COMPANIES_PAYMENT_SERVICE: '/HalfService/user/:id/companies/:companyId/paymentInfo'
};

export const TOAST_TYPE = {
  success: "success",
  error: "error",
  info: "info",
  warning: "warning",
  confirm: "confirm"
};

export const SOURCE_TYPE = {
  JAVA: 'java',
  NODE: 'node',
  BIG_PAY: 'bigpay',
  WORKFLOW: 'workflow',
  DOCHUB: 'dochub',
  DWOLLA: 'dwolla'
};

export enum PAGES {
  DASHBOARD = <any>'dashboard',
  COA = <any>'coa',
  COMPANIES = <any>'companies',
  VENDORS = <any>'vendors',
  WORKFLOW = <any>'workflow',
  CARD_REPOSITORY = <any>'cardRepository',
  NOTIFICATIONS = <any>'notifications',
  GROUPS = <any>'groups',
  REPORTS = <any>'reports',
};

export const NOTIFICATIONS = {
  SHARE_HEADERS:[{"name":"notification_text","displayName":"Notification","isSortable":false,"datatype":"string"},{"name":"notification_date","displayName":"Timestamp","isSortable":true,"datatype":"numeric","dataSortInitial":"descending"},{"name":"source_id","displayName":"Link","isSortable":false,"datatype":"string"},{"name":"notification_id","displayName":"notification_id","isSortable":false,"datatype":"string"}],
  COMMENT_HEADERS:[{"name":"notification_text","displayName":"Notification","isSortable":false,"datatype":"string"},{"name":"notification_date","displayName":"Timestamp","isSortable":true,"datatype":"numeric","dataSortInitial":"descending"},{"name":"source_id","displayName":"Link","isSortable":false,"datatype":"string"},{"name":"notification_id","displayName":"notification_id","isSortable":false,"datatype":"string"}],
  GROUP_HEADERS:[{"name":"notification_text","displayName":"Notification","isSortable":false,"datatype":"string"},{"name":"notification_date","displayName":"Timestamp","isSortable":true,"datatype":"numeric","dataSortInitial":"descending"},{"name":"source_id","displayName":"Link","isSortable":false,"datatype":"string"},{"name":"notification_id","displayName":"notification_id","isSortable":false,"datatype":"string"}],
  ALERT_HEADERS:[{"name":"notification_text","displayName":"Notification","isSortable":false,"datatype":"string"},{"name":"notification_date","displayName":"Timestamp","isSortable":true,"datatype":"numeric","dataSortInitial":"descending"},{"name":"source_id","displayName":"Link","isSortable":false,"datatype":"string"},{"name":"notification_id","displayName":"notification_id","isSortable":false,"datatype":"string"}]
};


export const GROUPS = {
  HEADERS:[
    {"name":"group_name","displayName":"Group Name","isSortable":true,"datatype":"string","dataHide":""},
    {"name":"user_id","displayName":"Group Owner","isSortable":false,"datatype":"string","dataHide":""},
    {"name":"creation_date","displayName":"Creation Date","isSortable":true,"datatype":"numeric","dataHide":"phone","dataSortInitial":"descending"},
    {"name":"members","displayName":"Members","isSortable":false,"datatype":"numeric","dataHide":"phone"}
  ]
};

export const COA_CATEGORY_TYPES = [
  {"value": "accountsReceivable", "name": "Accounts receivable (A/R)"},{"value": "bank", "name": "Bank"},
  {"value": "otherCurrentAssets", "name": "Other Current Assets"},{"value": "fixedAssets", "name": "Fixed Assets"},
  {"value": "otherAssets", "name": "Other Assets"},{"value": "accountsPayable", "name": "Accounts Payable(A/P)"},
  {"value": "creditCard", "name": "Credit Card"},{"value": "otherCurrentLiabilities", "name": "Other Current Liabilities"},
  {"value": "longTermLiabilities", "name": "Long Term Liabilities"},{"value": "equity", "name": "Equity"},
  {"value": "income", "name": "Income"},{"value": "otherIncome", "name": "Other Income"},
  {"value": "costOfGoodsSold", "name": "Cost of Goods Sold"},{"value": "expenses", "name": "Expenses"},
  {"value": "otherExpense", "name": "Other Expense"}
];

export const COA_SUBTYPES = {
  accountsReceivable: [{'value':'accountsReceivable', 'name':'Accounts Receivable(A/R)'}],
  otherCurrentAssets: [{'value':'allowanceForBadDebts', 'name':'Allowance for Bad Debts'},
    {'value':'developmentCosts', 'name':'Development Costs'},{'value':'employeeCashAdvances', 'name':'Employee Cash Advances'},{'value':'inventory', 'name':'Inventory'},
    {'value':'mortgageRealEstateLoans', 'name':'Investment- Mortgage/Real Estate Loans'},{'value':'taxExemptedSecurities', 'name':'Investment- Tax-Exempted securities'},
    {'value':'usGovernmentObligations', 'name':'Investment- U.S.Government Obligations'},{'value':'otherInvestments', 'name':'Investments- Others'},{'value':'loansToOfficers', 'name':'Loans to Officers'},
    {'value':'loansToOthers', 'name':'Loans to others'},{'value':'loansToStockholders', 'name':'Loans to stockholders'},{'value':'otherCurrentAssets', 'name':'Other current Assets'},
    {'value':'prepaidExpenses', 'name':'Prepaid Expenses'},{'value':'retainage', 'name':'Retainage'}],
  bank: [{'value':'cashOnHand', 'name':'Cash on hand'},{'value':'checking', 'name':'Checking'},{'value':'moneyMarket', 'name':'Money Market'},
    {'value':'rentsHeldInTrust', 'name':'Rents Held in Trust'},{'value':'savings', 'name':'Savings'},{'value':'trustAccount', 'name':'Trust account'}],
  fixedAssets: [{'value':'accumulatedAmortization', 'name':'Accumulated Amortization'},{'value':'accumulatedDepletion', 'name':'Accumulated Depletion'},
    {'value':'accumulatedDepreciation', 'name':'Accumulated Depreciation'}, {'value':'buildings', 'name':'Buildings'},{'value':'depletableAssets', 'name':'Depletable Assets'},
    {'value':'furnitureAndFixtures', 'name':'Furniture & Fixtures'},{'value':'intangibleAssets', 'name':'Intangible Assets'},{'value':'land', 'name':'Land'},
    {'value':'machineryEquipment', 'name':'Machinery & Equipment'},{'value':'leaseholdImprovements', 'name':'Leasehold Improvements'},{'value':'vehicles', 'name':'Vehicles'},
    {'value':'otherFixedAssets', 'name':'Other Fixed Assets'}],
  accountsPayable: [{'value':'accountsPayable', 'name':'Accounts Payable(A/P)'}],
  otherAssets: [{'value':'accumulatedAmortizationOfOtherAssets', 'name':'Accumulated Amortization of Other Assets'},{'value':'goodwill', 'name':'Goodwill'},
    {'value':'leaseBuyout', 'name':'Lease Buyout'},{'value':'licenses', 'name':'Licenses'},{'value':'organizationalCosts', 'name':'Organizational Costs'},
    {'value':'otherLongTermAssets', 'name':'Other Long-term Assets'},{'value':'securityDeposits', 'name':'Security Deposits'}],
  creditCard: [{'value': 'creditCard', 'name': 'Credit Card'}],
  otherCurrentLiabilities:[{'value': 'federalOncomeTaxPayable', 'name': 'Federal Income Tax Payable'},{'value': 'insurancePayable', 'name': 'Insurance Payable'},
    {'value': 'lineOfCredit', 'name': 'Line of Credit'},{'value': 'loanPayable', 'name': 'Loan Payable'},{'value': 'otherCurrentLiabilities', 'name': 'Other Current Liabilities'},
    {'value': 'payrollClearing', 'name': 'Payroll Clearing'},{'value': 'payrollTaxPayable', 'name': 'Payroll Tax Payable'},{'value': 'prepaidExpensesPayable', 'name': 'Prepaid Expenses Payable'},
    {'value': 'stateOrLocalIncomeTaxPayable', 'name': 'State/Local Income tax payable'},{'value': 'rentsInTrustLiability', 'name': 'Rents in trust-Liability'},
    {'value': 'salesTaxPayable', 'name': 'Sales tax payable'}],
  longTermLiabilities: [{'value': 'notesPayable', 'name': 'Notes Payable'},{'value': 'otherLongTermsLiabilities', 'name': 'Other Long Term Liabilities'},{'value': 'shareHolderNotesPayable', 'name': 'Shareholder Notes Payable'}],
  equity: [{'value': 'accumulatedAdjustment', 'name': 'Accumulated Adjustment'},{'value': 'commonStock', 'name': 'Common Stock'},{'value': 'openingBalanceEquity', 'name': 'Opening Balance Equity'},
    {'value': 'ownersEquity', 'name': 'Owner\'s Equity'},{'value': 'paidInCapitalOrSurplus', 'name': 'Paid-In Capital or Surplus'},{'value': 'partnerContributions', 'name': 'Partner Contributions'},
    {'value': 'partnerDistributions', 'name': 'Partner Distributions'},{'value': 'partnersEquity', 'name': 'Partner\'s Equity'},{'value': 'treasuryStock', 'name': 'Treasury Stock'},
    {'value': 'retainedEarnings', 'name': 'Retained Earnings'},{'value': 'preferredStock', 'name': 'Preferred Stock'}],
  income: [{'value': 'discountsRefundsGiven', 'name': 'Discounts/Refunds Given'},{'value': 'nonProfitIncome', 'name': 'Non-Profit Income'},{'value': 'otherPrimaryIncome', 'name': 'Other Primary Income'},
    {'value': 'salesOfProductIncome', 'name': 'Sales of Product Income'},{'value': 'servicesFeeIncome', 'name': 'Services/Fee Income'},{'value': 'unappliedCashPaymentIncome', 'name': 'Unapplied Cash Payment Income'}],
  otherIncome: [{'value': 'dividendIncome', 'name': 'Dividend Income'},{'value': 'interestEarned', 'name': 'Interest Earned'},{'value': 'otherInvestmentIncome', 'name': 'Other Investment Income'},
    {'value': 'otherMiscellaneousIncome', 'name': 'Other Miscellaneous Income'},{'value': 'interestEarned', 'name': 'Interest Earned'},{'value': 'taxExemptInterest', 'name': 'Tax-Exempt Interest'}],

  costOfGoodsSold: [{'value': 'costOfLaborCOS', 'name': 'Cost of labor - COS'},{'value': 'equipmentRental', 'name': 'Equipment Rental - COS'},{'value': 'otherCostsOfServices', 'name': 'Other Costs of Services - COS'},
    {'value': 'shippingFreightAndDelivery', 'name': 'Shipping, Freight & Delivery - COS'},{'value': 'suppliesAndMaterials', 'name': 'Supplies & Materials - COGS'}],

  expenses: [{'value': 'advertisingOrPromotional', 'name': 'Advertising/Promotional'},{'value': 'auto', 'name': 'Auto'},{'value': 'badDebts', 'name': 'Bad Debts'},
    {'value': 'bankCharges', 'name': 'Bank Charges'},{'value': 'charitableContributions', 'name': 'Charitable Contributions'},{'value': 'costOfLabor', 'name': 'Cost of Labor'},
    {'value': 'duesAndSubsriptions', 'name': 'Dues & subscriptions'},{'value': 'entertainment', 'name': 'Entertainment'}],
  otherExpense: [{'value': 'amortization', 'name': 'Amortization'},{'value': 'deprecation', 'name': 'Deprecation'},{'value': 'exchangeGainOrLoss', 'name': 'Exchange Gain or Loss'},
    {'value': 'otherMiscellaneousExpense', 'name': 'Other Miscellaneous Expense'},{'value': 'penaltiesAndSettlements', 'name': 'Penalties & Settlements'}]
};

export const SUBTYPE_DESCRIPTIONS = {
  accountsPayable:"<p><b>Accounts Payable</b>(also called A/P) tracks amounts you owe to your vendors and suppliers.</p><p>Qount Plus automatically creates one Accounts Payable account for you. Most businesses need only one.</p>",
  accountsReceivable:"<p><b>Accounts receivable</b> (also called A/R, Debtors, or Trade and other receivables) tracks money that customers owe you for products or services, and payments customers make.</p><p>Qount plus automatically creates one Accounts receivable account for you. Most buinesses need only one.</p><p>Each customer has a register, which functions like an Accounts receivable account for each customer.</p>",
  accumulatedAdjustment:"<p>S coporations use this account to track adjustments to owner's equity that are not attributable to net income.</p>",
  accumulatedAmortization:"<p>Use <b>Accumulated amortization</b> to track how much you amortize intangible assets.</p>",
  accumulatedAmortizationOfOtherAssets:"<p>Use <b>Accumulated amortization of other assets</b> to track how much you've amortized asset whose type is <b>Other Asset</b></p>",
  accumulatedDepletion:"<p>Use <b>Accumulated depletion</b> to track how much you deplete a natural resource.</p>",
  accumulatedDepreciation:"<p>Use <b>Accumulated Deprecation</b> to track how much you depreciate a fixed asset(a physical asset you do not expect to convert to cash during one year of normal operations)</p>",
  advertisingOrPromotional:"<p>User <b>Advertising/promotional</b> to track money spent promoting your company</p><p>you may want different accounts of this type to track different promotional efforts (Yellow Pages, newspaper, radio , flyers, events, and so on).</p>",
  allowanceForBadDebts:"<p>Use <b>Allowance for bad debts</b> to estimate the part of Accounts receivable you think you might not collect</p><p>Use this <b>only</b> if you are keeping your books on the accrual basis.</p>",
  amortization:"<p>Use <b>Amortization</b> to track amortization of intangible assets.</p><p>Amortization is spreading the cost of an intangible asset over its useful ief, like depreciation of fixed assets.</p><p>You may want an amortization account for each intangible asset you have.</p>",
  auto:"<p>Use <b>Auto</b> to track costs associated with vehicles.</p><p>You have want different accounts of this type to track gasoline, repairs, and maintenance.</p>If your business owns a car or truck, you may want to track its values as a Fixed Assets, in addition to tracking its expenses.<p>",
  badDebts:"<p>Use <b>Bad debt</b> to track debt you have written off.</p>",
  bankCharges:"<p>Use <b>Bank charges</b> for any fees you pay to financial institutions.</p>",
  buildings:"<p>Use <b>Buildings</b> to track the cost of structures you own and use for your business. If you have a business in your home, consult your accountant or IRS Publication 587.</p><p>Use a <b>Land</b> account for the land portion of any real property you own, splitting the cost of the property between land and building in a logical method. A common method is to mimic the land-to-building raio on the property tax statement</p>",
  cashOnHand:"<p>Use a <b>Cash on hand</b> account to track cash your company keeps for occasional expenses, also called petty cash.</p><p>To track cash from sales that have not been deposited yet, use a pre-created account called <b>Undeposited funds</b>, instead.</p>",
  charitableContributions:"<p>Use <b>Charitable contributions</b> to track gifts to charity.</p>",
  checking:"<p>Use <b>Checking</b> accounts to track all your checking activity, including debit card transactions.</p><p>Each checking account your company has at a bank or other finanical institution should have its own Checking type account in Qount.</p>",
  commonStock:"<p>Corporations use <b>Common stock</b> to track shares of its common stock in the hands of shareholders. The amount in this account should be stated (or par) values of the stock.</p>",
  costOfLabor:"<p>Use <b>Cost of labor</b> to track the cost of paying employees to produce products or supply services.</p><p>It includes all employment costs, including food and transportation, if applicable.</p><p>This account is also available as Cost of Goods Sold(COGS) account.</p>",
  costOfLaborCOS:"<p>Use <b>Cost of labor- COS</b> to track the cost of paying employees to produce products or supply services.</p><p>It includes all employment costs, including food and transportaion, if applicable.</p>",
  creditCard:"<p><b>Credit card</b> accounts track the balance due on your business credit cards.</p><p>Create one <b>Credit card</b> account for each credit card account your business uses.</p>",
  depletableAssets:"<p>Use <b>Depletable Assets</b> to track natural resources, such as timberlands, oil wells, and mineral deposits</p>",
  developmentCosts:"<p>Use <b>Development costs</b> to track amounts you deposit or set aside to arrange for financing , such as an SBA loan, or for deposits in anticipation of the purchase of property or other assets.</p><p>When the deposit is refunded, or the purchase takes place remove the amount from this account.</p>",
  deprecation:"<p>Use <b>Deprecation</b> to track how much you depreciate fixed assets.</p><p>You may want a depreciation account for each fixed asset you have.</p>",
  discountsRefundsGiven:"<p>Use <b>Discounts/refunds given</b> to track discounts you give to customers.</p><p>This account typically has a negative balance so it offsets other income.</p><p>For discounts from vendors, use an expense account, instead.</p>",
  dividendIncome:"<p>Use <b>Dividend income</b> to track taxable dividends from investments.</p>",
  duesAndSubsriptions:"<p>Use <b>Dues & subscriptions</b> to track dues & subscriptions related to running your business</p>.<p>You may want different accounts of this type for professional dues, fees for licenses that can't be transferred, magazines, newspapers, industry publications, or service subscriptions.</p>",
  employeeCashAdvances:"<p>Use <b>Employee cash advances</b> to track employee wages and salary you issue to an employee early, or other non-salary money given to employees.</p> <p>If you make a loan to an employee, use the Other current asset account type called <b>Loans to other</b> instead</p>",
  entertainment:"<p>Use <b>Entertainment</b> to track events to entertain employees.</p><p>If the event is a meal, use <b>Entertainment means</b>, instead.</p>",
  entertainmentMeals: '<p>Use <b>Entertainment meals</b> to track how much you spend on dining with your employees to promote morale.</p><p>If you dine with a customer to promote your business, use a <b>Promotional Meals</b> account, instead.</p>',
  equipmentRental:"<p>Use <b>Equipment rental</b> to track the cost of renting equipment to produce products or services.</p><p>This account is also available as a Cost of Goods(COGS) account.</p><p>If you purchase equipment, use a Fixed Asst account type called <b>Machinery and equipment</b>.</p>",
  exchangeGainOrLoss:"<p>Use <b>Exchange Gain or Loss</b> to track gains or losses that occur as a result of exchange rate fluctuations.</p>",
  federalOncomeTaxPayable:"<p>Use <b>Federal Income Tax Payable</b> if your business is a corporation, S corporation, or limited partnership keeping records on the accrual basis.</p><p>This account tracks income tax liabilities in the year the income is earned.</p>",
  furnitureAndFixtures:"<p>Use <b>Furniture & fixtures</b> to track any furniture and fixtures your business owns and uses, like a dental chair or sales booth.</p>",
  goodwill:"<p>Use <b>Goodwill</b> only if you have acquired another company. It represents the intagible assets of the acquired company which gave it an advantage such as favorable government relations, business name, outstanding credit ratings, location, superior management, customer lists, product quality, or good labor relations.</p>",
  insurancePayable:"<p>Use <b>Insurance payable</b> to keep track of insurance amounts due.</p><p>This account is most useful for the businesses with monthly recurring insurance expenses such as Workers Compensation.</p>",
  intangibleAssets:"<p>Use <b>Intangible Assts</b> to track intangible assts that you plan to amortize. Examples include franchises, customer lists, copyrights, and patents.</p>",
  interestEarned:"<p>Use <b>Interest earned</b> to track interest from bank or savings accounts, investments, or interest payments to you on loans your business made.</p>",
  interestPaid:"<p>Use <b>Interest paid</b> for all types of interest you pay, including mortgage interest, finance charges on credit cards, or interest on loans.</p>",
  inventory:"<p>Use <b>Inventory</b> to track the cose of goods your business purchased for resale.</p><p>When the goods are sold, assign the sale to a <b>Cost of goods sold</b> account.</p>",
  insurance: "<p>Use <b>Insurance</b> to track insurance payments.</p><p>You may want different accounts of this type for different types of insurance(auto, general liability, and so on).</p>",
  land:"<p>Use <b>Land</b> for land or property you don't depreciate.</p><p>If land and building were accquired together, split the cost between the two in a logical way. One common method is to use the land-to-building ratio on the property tax statement.</p><p>For land you use as a natural resource, use a <b>Depletable assets</b> account, instead.</p>",
  leaseBuyout:"<p>Use <b>Lease buyout</b> to track lease payments to be applied toward the purchase of a leased asset.</p><p>You don't tract the leased asset itself until you purchase it.</p>",
  leaseholdImprovements: "<p>Use <b>Leasehold improvements</b> to track improvements to a leased asset that increases the asset's value. For example, if you carpet a leased office space and are not reimbursed, that's a leashold improvemnt.</p>",
  licenses:"<p>Use <b>Licenses</b> to track non-professional licenses for permission to engage in an activity, like selling alcohol or radio broadcasting.</p><p>For fees associated with professional license granted to individuals, use a <b>Legal & professional fees</b> expense account instead.</p>",
  lineOfCredit:"<p>Use <b>Line of credit</b> to track the balance due on any lines of credit your business has. Each line of credit your business has should have its own <b>Line of credit account</b>.</p>",
  loansToOfficers: "<p>If you operate your business as a Corporation or S Corporation, use <b>Loans to officers</b> to track money loaned to officers of your business.</p>",
  loansToOthers: "<p>Use <b>Loans to others</b> to track money your business loans to other people or businesses.</p><p>This type of acount is also referred to as Notes Receivable.</p><p>For early slary payments to employees, use Employee cash advances, instead.</p>",
  loansToStockholders: "<p>If you operate your business as a Corporation or S Corporation, use <b>Loans to stockholders</b> to track money your business loans to its stockholders.</p>",
  loanPayable:"<p>Use <b>Loan payable</b> to track loans your business owes which are payable within the next twelve months.</p><p>For longer-term loans, use the Long-term liability called <b>Notes payable</b>, instead.</p>",
  machineryEquipment: "<p>Use <b>Machinery & quipment</b> to track computer hardware, as well as any other non-furniture fixtures or devices owned and used for your business.</p><p>This includes equipment that you ride, like tractors, and lawn mowers. Cards and trucks, however, should be tracked with <b>Vehicle accounts</b>, instead.</p>",
  moneyMarket:"<p>Use <b>Money Market</b> to track amounts in money market accounts.</p><p>For investments, see <b>Other Current Assets</b>, instead.</p>",
  mortgageRealEstateLoans:"<p>Use <b>Investments - Mortgage/real estate loans</b> to show the balances of any mortgage or real estate loans your business has made or purchased.</p>",
  nonProfitIncome:"<p>Use <b>Non-profit income</b> to track money coming in if you are a non-profit organization.</p>",
  notesPayable:"<p>Use <b>Notes payable</b> to track the amounts your business owes in long-term (over twelve months)loans.</p><p>For shorter loans, use the Other current liability account type called <p>Loan Payable</p> instead.</p>",
  openingBalanceEquity:"<p>Qount plus creates this account the first time you enter an opening balance for a balance sheet account.</p><p>As your enter opening balances, Qount Plus records the amounts in <b>Opening balance equity</b>. This ensures that you have a correct balance sheet for your company, even before you've finished entering all your company's assets and liabilities.</p>",
  organizationalCosts:"<p>Use <b>Organizational costs</b> to track costs incurred when forming a partnership or corporation.</p><p>The costs include the legal and accounting costs necessary to organize the company, facilitate the filings of the legal documents, and other paperwork.</p>",
  otherCostsOfServices:"<p>Use <b>Other costs of services - COS</b> to track costs related to services you provide that don't fall into another Cost of Goods Sold type.</p>",
  otherCurrentAssets: "<p>Use <b>Other current assets</b> for current assets not covered by the other types. Current assets are likely to be converted to cash or used up in a year.</p>",
  otherCurrentLiabilities:"<p>Use <b>Other current liabilities</b> to track liabilities due within the next twelve months that do not fit the Other current liability account types.</p>",
  otherFixedAssets: "<p>Use <b>Other fixed asset</b> for fixed assets that are not covered by other asset types.</p><p>Fixed assets are physical property that you use in your business and that you do not expect to convert to cash or be used up during one year of normal operations.</p>",
  otherInvestmentIncome:"<p>Use <b>Other investment income</b> to track other types of investment income that isn't from dividends or interest.</p>",
  otherInvestments:"<p>Use <b>Investments-Other</b> to track the value of investments not covered by other investment account types. Examples include publicly-traded stocks, coins or gold.</p>",
  otherLongTermAssets:"<p>Use <b>Other long-term assets</b> to track assets not covered by other types.</p><p>Long-term assets are expected to provide values for more than one year.</p>",
  otherLongTermsLiabilities:"<p>Use <b>Other long term liabilities</b> to track liabilities due in more than twelve months that don't fit the other Long-term liability account types.</p>",
  otherMiscellaneousExpense:"<p>Use <b>Other miscellaneous expense</b> to track unusual or infrequent expenses that don't fall into another Other Expense type.</p><p>If an expense is directly related to providing a service, use an Expense type (not an Other Expense type) account called <b>Other miscellaneous service cost</b>.</p>",
  otherMiscellaneousIncome:"<p>Use <b>Other miscellaneous income</b> to track income that isn't from normal business operations, and doesn't fall into another Other income type.</p>",
  otherPrimaryIncome:"<p>Use <b>Other primary income</b> to track income from normal business operations that doesn't fall into another Income type</p>",
  ownersEquity:"<p>S corporations use <b>Owner's equity</b> to show the cumulative net income or loss of their business as of the beginning of the fiscal year.</p>",
  paidInCapitalOrSurplus:"<p>Corporations use <b>Paid-in capital</b> to track amounts received from shareholders in exchange for stock that are over and above the stock's stated (or par) value.</p>",
  partnerContributions:"<p>Partnerships use <b>Partner contributions</b> to track amounts partners contribute to the partnership during the year.</p>",
  partnerDistributions:"<p>Partnerships use <b>Partner distributions</b> to track amounts distributed by the partnership to its partners during the year.</p><p>Don't use this for regular payments to partner for interest of service. For regular payments, use a Guaranteed payments account(a Expense account in payroll expenses), instead.</p>",
  partnersEquity:"<p>Partnerships use <b>Partner's equity</b> to show the income remaining in the partnership for each partner as of the end of the prior year.</p>",
  payrollClearing:"<p>Use <b>Payroll clearing</b> to keep track of any non-tax amounts that you have deducted from employee paychecks or that you owe as a result of doing payroll. When you forward money to the appropriate vendors, deduct the amount from the balance of this account.</p><p>Do not use this account for tax amounts you have withheld or owe from paying employee wages. For those amounts, use the <b>Payroll tax payable</b> account instead.</p>",
  payrollTaxPayable:"<p>Use <b>Payroll tax payable</b> to keep track of tax amounts that you owe to Federal, State, and Local government agencies as a result of paying wages and taxes you have withheld from employee paychecks. When you forward the money to the government agency, deduct the amount from the balance of this account.</p>",
  penaltiesAndSettlements:"<p>Use <b>Penalties & settlements</b> to track money you pay for violating laws or regulations, setting laswsuits, or other penalties.</p>",
  preferredStock: "<p>Corporations use this account to track shares of its preferred stock in the hands of shareholders. The amount in this account should be the stated (or par)< value of the stock./p>",
  prepaidExpenses: "<p>Use <b>Prepaid expenses</b> to track payments for expenses that you won't recognize until your next accounting period.</p><p>When you recognize the expense, make a journal entry to transfer money from this account to the expense account.</p>",
  prepaidExpensesPayable:"<p>Use <b>Prepaid expenses payable</b> to track items such as property taxes that are due, but not yet deductible as an expense because the period they cover has not yet passed.</p>",
  rentsHeldInTrust:"<p>Use <b>Rents held in trust</b> to track deposits and rend held on behalf of the property owners.</p><p>Typically only property managers use this type of account.</p>",
  rentsInTrustLiability: "<p>Use <b>Rents in trust - liability</b> to offset the <b>Rents in trust</b> amount in assets.</p><p>Amounts in these accoutns are held by your business on behalf of others. They do not belong to your business, so should not appear to be yours on your balance sheet. This 'contra' account takes care of that  as long as the two balances match.</p>",
  retainage: "<p>Use <b>Retainage</b> if your customers regularly hold back a portion of a contract amount until you have completed a project.</p><p>This type of account is often used in the construction industry, and only if you record income on an accrual basis.</p>",
  retainedEarnings: "<p>Qount plus adds this account when you create your company.</p><p><b>Retained earnings</b> tracks net income from previous fiscal years.</p><p>Qount plus automatically transfers your profit(or loss) to <b>Retained earnings</b> at the end of each fiscal year.</p>",
  salesOfProductIncome:"<p>Use <b>Sales of product income</b> to track income from selling products.</p><p>This can include all kinds of products, like crops and livestock, rental fees performances, and food served.</p>",
  salesTaxPayable: "<p>Use <b>Sales tax payable</b> to track sales tax you have collected, but not yet remitted to the IRS.</p>",
  savings:"<p>Use <b>Savings</b> accounts to track your savings and CD activity.</p><p>Each savings account your company has at a bank or other financial institution should have its own savings type account.</p><p>For investments, see <b>Other Current Assets</b>, instead</p>",
  securityDeposits:"<p>Use <b>Security deposits</b> to track funds you've paid to cover any potential costs incurred by damage, loss, or theft.</p><p>The funds should be returned to you at the end of the contract.</p><p>If you collect deposits, use an <b>Other current liabilities</b> account type (an Other current liability account).</p>",
  servicesFeeIncome:"<p>Use <b>Service/fee income</b> to track income from services you perform or ordinary usage fees you charge.</p><p>For fees customers pay you for late payments or other uncommon situations, use an Other Income account type called <b>Other miscellaneous income</b>, instead.</p>",
  shareHolderNotesPayable:"<p>Use <b>Shareholder notes payable</b> to track long-term loan balances your business owes its shareholders.</p>",
  shippingFreightAndDelivery:"<p>Use <b>Shipping, frieght & delivery - COGS</b> to track the cost of shipping products to customers and distributors.</p>",
  suppliesAndMaterials:"<p>Use <b>Supplies & materials - COGS</b> to track the cost of raw goods and parts used or consumed when producing a product or providing a service.</p>",
  stateOrLocalIncomeTaxPayable:"<p>Use <b>State/Local income tax payable</b> if your business is a corporation, S corporation, or limited partnership keeping records on the accrual basis.</p><p>This account tracks income tax liabilities in the year the income is earned.</p>",
  taxExemptInterest:"<p>Use <b>Tax-exempt contributions</b> to record interest that isn't taxable, such as interest on money in tax-exempt retirement accounts, or interest from tax-exempt bonds.</p>",
  taxExemptedSecurities:"<p>Use <b>Investments - Tax-exempt securities</b> for investments in state and local bonds, or mutual funds that invest in state and local bonds.</p>",
  treasuryStock: "<p>Corporations use <b>Treasury stock</b> to track amounts paid by the corporation to buy its own stock back from sharedholders.</p>",
  trustAccount:"<p>Use <b>Trust accounts</b> for money held by you for the benefit of someone else.</p><p>For example, trust accounts afe often used by attrneys to keep track of expense money their customers have given them.<p>Often, to keep the amount in a trust account from looking like it's yours, the amount is offset in a 'contra' liability account(a Current Liability).</p>",
  unappliedCashPaymentIncome:"<p><b>Unapplied Cash Payment Income</b> reports the <b>Cash Basis</b> income from the customers payments you've received but not applied to invoices or charges. In general, you would never this directly on a purchase or slave transaction. The ORS calls this 'Constructive Receipt' Income. Se Publication 538.</p>",
  undepositedFunds: "<p>Use <b>Undeposited funds</b> for cash or checks from sales that haven't been deposited yet.</p><p>For petty cash, use Cash on hand, instead.</p>",
  usGovernmentObligations:"<p>Use <b>Investments - U.S.government obligations</b> for bongs issued by the U.S. government.</p>",
  vehicles: "<p>Use <b>Vehicles</b> to track the value of vehicles your business owns and uses for business. This includes off-road vehicles, air planes, helicopters, and boats.</p><p>If you use a vehicle for both business and personal use, consult your accountant or the IRS to see how you should track its value.</p>"
};
